digital_solar/urls.py
from .views import digital_volt, report
from django.urls import path

app_name = 'digital_solar'

urlpatterns = [
    path('v1/', digital_volt.as_view()),
    path(r'report', report, name='report'),
]

home/urls.py
from . import views
from django.urls import include
from django.urls import path as url
from rest_framework.authtoken.views import obtain_auth_token

app_name = 'home'

urlpatterns = [
    url(r'', views.home, name='home'),
    url(r'about', views.about, name='about'),
    url(r'service', views.service, name='service'),
    url(r'portfolio', views.portfolio, name='portfolio'),
    url(r'download', views.download, name='download'),
    # url(r'report', views.report, name='report'),
    url(r'contact/', views.contact, name='contact'),
    url(r'contactF/', views.contactF, name='contactF'),
    url('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    url('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

smartsanthe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('digital_solar.urls')),

    path(r'', include('home.urls')),
    path(r'about', include('home.urls')),
    path(r'service', include('home.urls')),
    path(r'portfolio', include('home.urls')),
    path(r'download', include('home.urls')),
    path(r'contact', include('home.urls'))
]

digital_solar/models.py
from django.db import models
# from djangodoo.models import OdooModel
# Create your models here.


class Panels(models.Model):

    panels_id = models.CharField(max_length=200)
    wat = models.IntegerField()
    max_volt = models.IntegerField()
    panel_dim = models.CharField(max_length=200)

    class Meta:
        # otherwise we get "Tutorial Seriess in admin"
        verbose_name_plural = "Panels"

    def __str__(self):
        return self.panels_id


class Device(models.Model):

    device_id = models.CharField(max_length=200)
    panels_id = models.CharField(max_length=200)
    logitude = models.FloatField()
    latitude = models.FloatField()

    class Meta:
        verbose_name_plural = "Device"

    def __str__(self):
        return self.device_id


class Customer(models.Model):
    bill_no = models.CharField(max_length=200)
    bill_date = models.DateField()
    ammount = models.IntegerField()
    owner_name = models.CharField(max_length=200)
    tt_divice = models.IntegerField()
    tt_panels = models.IntegerField()
    service_status = models.IntegerField(default='')
    address = models.CharField(max_length=200, default='')
    mobile = models.CharField(max_length=10, default='')
    device_id = models.ForeignKey('Device', related_name='Device', on_delete=models.CASCADE)
    panels_id = models.ForeignKey('Panels', related_name='Panels', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Customer"

    def __str__(self):
        return self.bill_no


class Voltages(models.Model):

    volt = models.IntegerField()
    temperature = models.FloatField()
    insertdate = models.DateTimeField()
    location = models.CharField(max_length=200)
    bill_no = models.CharField(max_length=200)
    panel_id = models.CharField(max_length=200)
    device_id = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = "Voltages"

    def __str__(self):
        return str(self.volt)

home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

home/forms.py
# from django import forms
#
# class ContactForm(forms.Form):
#     full_name = forms.CharField()
#     email = forms.EmailField()
#     message = forms.CharField()

digital_solar/views.py
<<<<<<< HEAD
# import numpy as np
import io, base64
import matplotlib.pyplot as plt
=======
>>>>>>> d30691f5c0e19ed94123b6666cb79c2a9e9e1b93

import io, base64
from . import models
from .models import Voltages
import matplotlib.pyplot as plt
from rest_framework import status
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import VoltageSerializer
from rest_framework.permissions import IsAuthenticated


def report(request):

    data = models.Voltages.objects.all()
    print("report")
    s = []
    t = []
    for i in data:
        s.append(i.volt)
        t.append(i.insertdate)
    # max_year = models.Voltages.objects.latest('time_instance')


    fig, ax = plt.subplots()
    ax.plot(t[-5:], s[-5:])

    ax.set(xlabel='time (s)', ylabel='voltage (mV)',
           title='About as simple as it gets, folks')
    ax.grid()

    flike = io.BytesIO()
    fig.savefig(flike)
    b64 = base64.b64encode(flike.getvalue()).decode()

    return render(request, 'home/plotxxreport.html',
                  { "chart": b64}, status=200)


class digital_volt(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request, *args, **kwargs):

        result = Voltages.objects.all()
        serializers = VoltageSerializer(result, many=True)
        return Response({'status': 'success', "Voltages": serializers.data}, status=200)

    def post(self, request):
        serializer = VoltageSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response({"status": "success", "data": serializer.data}, status=status.HTTP_200_OK)
        else:
            return Response({"status": "error", "data": serializer.errors}, status=status.HTTP_400_BAD_REQUEST)

home/views.py
from django.shortcuts import render

from django.core.mail import send_mail
#from .forms import ContactForm

def home(request):
    print("home called")
    return render(request, 'home/index.html')


def about(request):
    return render(request, 'home/about-us.html')


def service(request):
    return render(request, 'home/services.html')


def portfolio(request):
    return render(request, 'home/portfolio.html')


def download(request):
    return render(request, 'home/desktopWMS.html')




def contact(request):
    return render(request, 'home/contact-us.html')

def contactF(request):
    #return render(request, 'home/contact-us.html')
    if request.method == "POST":
        name_form = request.POST.get('name')
        email_form = request.POST.get('email')
        message_form = request.POST.get('message')

        # query = request.GET.post("q")

        # send_mail('test email', message_form + email_form, email_form, ['oksmailsoft@gmail.com'])

        # form = ContactForm
    # return render(request, 'home/contact-us.html', {'form': form})
    return render(request, 'home/contact-us.html')

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | Smart Santhe</title>
    {% load static  %}
    <link href="{% static 'home/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'home/css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'home/css/main.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
    {% block stat %}
    {% endblock %}

    <link href="{% static 'home/css/wmstly.css' %}" rel="stylesheet">

    <script src="{% static 'home/js/html5shiv.js' %}"></script>
    <script src="{% static 'home/js/respond.min.js' %}"></script>
    <![endif]-->
    <link rel="shortcut icon" href="{% static 'home/images/ico/favicon.ico' %}">
   <!-- <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'home/images/ico/apple-touch-icon-144-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'home/images/ico/apple-touch-icon-114-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'home/images/ico/apple-touch-icon-72-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'home/images/ico/apple-touch-icon-57-precomposed.png' %}">-->
</head><!--/head-->
<body>
    <header class="navbar navbar-inverse navbar-fixed-top wet-asphalt" role="banner" > <!--style="height: 80px;"  -->
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home:home' %}"><img src="{% static 'home/images/logo.png' %}" alt="logo" vspace="10" hspace="20"></a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="{% block albums_home %}{% endblock %}"><a href="{% url 'home:home' %}">Home</a></li><!--class="{% block albums_active %}{% endblock %}"  class="active"-->
                    <li class="{% block albums_about %}{% endblock %}"><a href="{% url 'home:about' %}">About Us</a></li>
                    <li class="{% block albums_service %}{% endblock %}"><a href="{% url 'home:service' %}">Services</a></li>
                    <li class="{% block albums_portfolio %}{% endblock %}"><a href="{% url 'home:portfolio' %}">Portfolio</a></li>
                    <li class="{% block albums_download %}{% endblock %}"><a href="{% url 'home:download' %}">Download</a></li>
                    <li class="{% block report %}{% endblock %}"><a href="{% url 'digital_solar:report' %}">Report</a></li>

                    <!--<li class="dropdown">
                        <a href="{% static 'home/#" class="dropdown-toggle" data-toggle="dropdown">Pages <i class="icon-angle-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% static 'home/career.html">Career</a></li>
                            <li><a href="{% static 'home/blog-item.html">Blog Single</a></li>
                            <li><a href="{% static 'home/pricing.html">Pricing</a></li>
                            <li><a href="{% static 'home/404.html">404</a></li>
                            <li><a href="{% static 'home/registration.html">Registration</a></li>
                            <li class="divider"></li>
                            <li><a href="{% static 'home/privacy.html">Privacy Policy</a></li>
                            <li><a href="{% static 'home/terms.html">Terms of Use</a></li>
                        </ul>
                    </li>
                    <li><a href="{% static 'home/blog.html">Blog</a></li>
                    -->
                    <li class="{% block albums_contact %}{% endblock %}"><a href="{% url 'home:contact' %}">Contact</a></li>
                </ul>
            </div>
        </div>
    </header><!--/header-->
    {% block body %}
    {% endblock %}
    <section id="bottom" class="wet-asphalt">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <h4>About Us</h4>
                    <p>It is magnificent to grow old, if one keeps young. </p><p>
			Our team constantly interact with clients for perfection to the work we pick and giving the service beyond the contract.</p>

                </div><!--/.col-md-3-->

                <div class="col-md-3 col-sm-6">
                    <h4>Company</h4>
                    <div>
                        <ul class="arrow">
                            <li><a href="#">Company Overview</a></li>
                            <li><a href="#">Meet The Team</a></li>
                            <li><a href="#">Our Awesome Partners</a></li>
                            <li><a href="#">Our Services</a></li>
                            <li><a href="#">Frequently Asked Questions</a></li>
                            <li><a href="#">Conatct Us</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Terms of Use</a></li>
                            <li><a href="#">Copyright</a></li>
                        </ul>
                    </div>
                </div><!--/.col-md-3-->
<!--
                <div class="col-md-3 col-sm-6">
                    <h4>Latest Blog</h4>
                    <div>
                        <div class="media">
                            <div class="pull-left">
                                <img src="{% static 'home/images/blog/thumb1.jpg" alt="">
                            </div>
                            <div class="media-body">
                                <span class="media-heading"><a href="{% static 'home/#">Pellentesque habitant morbi tristique senectus</a></span>
                                <small class="muted">Posted 17 Aug 2013</small>
                            </div>
                        </div>
                        <div class="media">
                            <div class="pull-left">
                                <img src="{% static 'home/images/blog/thumb2.jpg" alt="">
                            </div>
                            <div class="media-body">
                                <span class="media-heading"><a href="{% static 'home/#">Pellentesque habitant morbi tristique senectus</a></span>
                                <small class="muted">Posted 13 Sep 2013</small>
                            </div>
                        </div>
                        <div class="media">
                            <div class="pull-left">
                                <img src="{% static 'home/images/blog/thumb3.jpg" alt="">
                            </div>
                            <div class="media-body">
                                <span class="media-heading"><a href="{% static 'home/#">Pellentesque habitant morbi tristique senectus</a></span>
                                <small class="muted">Posted 11 Jul 2013</small>
                            </div>
                        </div>
                    </div>
                </div><!--/.col-md-3-->

                <div class="col-md-3 col-sm-6">
                    <h4>Address</h4>
                    <address>
                        <strong>Smart Santhe</strong><br>
                        Bangalore<br>
                        <abbr title="Phone">P:</abbr> (+91) 888 407 7926
                    </address>
<!--                    <h4>Newsletter</h4>
                    <form role="form">
                        <div class="input-group">
                            <input type="text" class="form-control" autocomplete="off" placeholder="Enter your email">
                            <span class="input-group-btn">
                                <button class="btn btn-danger" type="button">Go!</button>
                            </span>
                        </div>
                    </form> -->
                </div> <!--/.col-md-3-->

                <div class="col-md-3 col-sm-6">
                <h4>Our Location</h4>
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15549.25578554625!2d77.66857057144135!3d13.015668703230332!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae1121d646a235%3A0xbf0eec5468808a4f!2sRamamurthy+Nagar%2C+Bengaluru%2C+Karnataka+560016!5e0!3m2!1sen!2sin!4v1488877464191"
                        width="300" height="245" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div><!--/.col-sm-4-->

            </div>
        </div>
    </section><!--/#bottom-->

    <footer id="footer" class="midnight-blue">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    &copy; 2013 <a target="_blank" href="http://shapebootstrap.net/" title="Free Twitter Bootstrap WordPress Themes and HTML templates">ShapeBootstrap</a>. All Rights Reserved.
                </div>
                <div class="col-sm-6">
                    <ul class="pull-right">
                        <li><a href="{% url 'home:home' %}">Home</a></li>
                        <li><a href="{% url 'home:about' %}">About Us</a></li>
                       <!-- <li><a href="{% static 'home/#">Faq</a></li>-->
                        <li><a href="{% url 'home:contact' %}">Contact Us</a></li>
                        <li><a id="gototop" class="gototop" href="{% static 'home/#"><i class="icon-chevron-up"></i></a></li><!--#gototop-->
                    </ul>
                </div>
            </div>
        </div>
    </footer><!--/#footer-->

    <script src="{% static 'home/js/jquery.js' %}"></script>
    <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'home/js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'home/js/jquery.isotope.min.js' %}"></script>
    <script src="{% static 'home/js/main.js' %}"></script>
</body>
</html>

home/templates/home/contact-us.html
{% extends 'home/base.html' %}
{% load static  %}
{% block albums_contact %}active{% endblock %}
{% block body %}

    <section id="title" class="emerald">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h1>Contact Us</h1>
                    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada</p>
                </div>
                <div class="col-sm-6">
                    <ul class="breadcrumb pull-right">
                        <li><a href="{% url 'home:home' %}">Home</a></li>
                        <li class="active">Contact Us</li>
                    </ul>
                </div>
            </div>
        </div>
    </section><!--/#title-->    

    <section id="contact-page" class="container">
        <div class="row">
            <div class="col-sm-8">
                <h4>Contact Form</h4>
                <div class="status alert alert-success" style="display: none"></div>
                <form  method="post" action="{% url 'home:contactF' %}" role="form"><!--id="main-contact-form" class="contact-form" name="contact-form"-->
                {% csrf_token %}
                    <div class="row">
                        <div class="col-sm-5">
                            <div class="form-group">
                                <input type="text" class="form-control" required="required" placeholder="First Name" name="name">
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" required="required" placeholder="Last Name">
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" required="required" placeholder="Email address" name="email">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary btn-lg">Send Message</button>
                            </div>
                        </div>
                        <div class="col-sm-7">
                            <textarea name="message" id="message" required="required" class="form-control" rows="8" placeholder="Message"></textarea>
                        </div>
                    </div>
                </form>
            </div><!--/.col-sm-8-->
            <div class="col-sm-4">
                <h4>Our Location</h4>
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15549.25578554625!2d77.66857057144135!3d13.015668703230332!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae1121d646a235%3A0xbf0eec5468808a4f!2sRamamurthy+Nagar%2C+Bengaluru%2C+Karnataka+560016!5e0!3m2!1sen!2sin!4v1488877464191"
                        width="420" height="245" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div><!--/.col-sm-4-->
        </div>
    </section><!--/#contact-page-->
{% endblock %}

home/templates/home/desktopWMS.html
{% extends 'home/base.html' %}

{% block albums_download %}active{% endblock %}
{% load static  %}

    {% block stat %}
    <link href="{% static 'home/css/wmstly.css' %}" rel="stylesheet">
    {% endblock %}

{% block body %}

<body>

<script src="{% static 'home/js/jscript.js' %}"></script>

<style>
.jssora05l,.jssora05r{display:block;position:absolute;

width:40px;height:40px;cursor:pointer;background:url("{% static 'home/img/a17.png' %}") no-repeat;
overflow:hidden}
.jssora05l{background-position:-10px -40px}
.jssora05r{background-position:-70px -40px}.jssora05l:hover{background-position:-130px -40px}
.jssora05r:hover{background-position:-190px -40px}.jssora05l.jssora05ldn{background-position:-250px -40px}
.jssora05r.jssora05rdn{background-position:-310px -40px}
.jssora05l.jssora05lds{background-position:-10px -40px;opacity:.3;pointer-events:none}
.jssora05r.jssora05rds{background-position:-70px -40px;opacity:.3;pointer-events:none}
.jssort01 .p{position:absolute;top:0;left:0;width:72px;height:72px}
.jssort01 .t{position:absolute;top:0;left:0;width:100%;height:100%;border:none}
.jssort01 .w{position:absolute;top:0;left:0;width:100%;height:100%}
.jssort01 .c{position:absolute;top:0;left:0;width:68px;height:68px;border:#000 2px solid;
box-sizing:content-box;
background:url("{% static 'home/img/t01.png' %}") -800px -800px no-repeat;
_background:none}.jssort01 .pav .c{top:2px;_top:0;left:2px;_left:0;width:68px;height:68px;border:#000 0 solid;
_border:#fff 2px solid;background-position:50% 50%}
.jssort01 .p:hover .c{top:0;left:0;width:70px;height:70px;border:#fff 1px solid;background-position:50% 50%}
.jssort01 .p.pdn .c{background-position:50% 50%;width:68px;height:68px;
border:#000 2px solid}* html .jssort01 .c,* html .jssort01 .pdn .c,* html .jssort01 .pav .c{width:72px;height:72px}
</style> <!-- width: 490px; height: 310px; -->

<section id="title" class="emerald">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h1>Free Download</h1>
                    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada</p>
                </div>
                <div class="col-sm-6">
                    <ul class="breadcrumb pull-right">
                        <li><a href="{% url 'home:home' %}">Home</a></li>
                        <li class="active">Download</li>
                    </ul>
                </div>
            </div>
        </div>
</section><!--/#title-->

<div class="row">

		<div class="col-md-7 col-md-offset-2">
			<h3>&nbsp; Free Bulling Software</h3>
<br>
			<p>Software to maintain day to day transaction of Retail shop. Having Barcode and quick reports
                helps the merchant handle products efficiently. And High security features are implemented to keep data safe.</p>
	    </div>

        <div class="col-md-7 col-md-offset-2"><h3>&nbsp;&nbsp;Windows Download :</h3><br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a class="btn btn-primary btn-lg"  href="{% static 'home/exe/OKsMail.exe' %}" download> Download OKSMAIL</a>
			<br><br><h5> OKsMail_Win7_64bit     <spans color:#2343eb >File size 17kb </spans></h5>
    			<p>The Software is Tested in Windows 7 and 8 (64 - Bit only),
                    on request we will provide The software compatible for your Operating system</p>
            <p>Default username / password is "Admin"</p>
		</div>

</div>
<hr>

<!--
<div class="row">
            <div class="col-lg-12">


<div class="well text-center">
    Reach us @  +91 7829779915     </div>
            </div>
            &lt;!&ndash; /.col-lg-12 &ndash;&gt;
        </div>
        &lt;!&ndash; /.row &ndash;&gt;

        &lt;!&ndash; Content Row &ndash;&gt;
-->
<br><br>
<div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 800px; height: 456px; overflow: hidden; visibility: hidden; background-color: #24262e;">
<!-- Loading Screen -->
<div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
<div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
<div style="position:absolute;display:block;background:url("{% static 'home/img/loading.gif' %}") no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
</div>
<div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 800px; height: 356px; overflow: hidden;">
<div data-p="144.50">
<img data-u="image" src="{% static 'home/img/01.jpg' %}" />
<img data-u="thumb" src="{% static 'home/img/thumb-01.jpg' %}" />
</div> <!--
<div data-p="144.50" style="display: none;">
<img data-u="image" src="{% static 'home/img/02.jpg' %}" />
<img data-u="thumb" src="{% static 'home/img/thumb-02.jpg' %}" />
</div> -->
<div data-p="144.50" style="display: none;">
<img data-u="image" src="{% static 'home/img/03.jpg' %}" />
<img data-u="thumb" src="{% static 'home/img/thumb-03.jpg' %}" />
</div>
<div data-p="144.50" style="display: none;">
<img data-u="image" src="{% static 'home/img/04.jpg' %}" />
<img data-u="thumb" src="{% static 'home/img/thumb-04.jpg' %}" />
</div>
<div data-p="144.50" style="display: none;">
<img data-u="image" src="{% static 'home/img/05.jpg' %}" />
<img data-u="thumb" src="{% static 'home/img/thumb-05.jpg' %}" />
</div>
<div data-p="144.50" style="display: none;">
<img data-u="image" src="{% static 'home/img/06.jpg' %}" />
<img data-u="thumb" src="{% static 'home/img/thumb-06.jpg' %}" />
</div>
<!-- <a data-u="any" href="http://www.jssor.com" style="display:none">Image Gallery</a> -->
<div data-p="144.50" style="display: none;">
<img data-u="image" src="{% static 'home/img/07.jpg' %}" />
<img data-u="thumb" src="{% static 'home/img/thumb-07.jpg' %}" />
</div>
<div data-p="144.50" style="display: none;">
<img data-u="image" src="{% static 'home/img/08.jpg' %}" />
<img data-u="thumb" src="{% static 'home/img/thumb-08.jpg' %}" />
</div> 
<div data-p="144.50" style="display: none;">
<img data-u="image" src="{% static 'home/img/09.jpg' %}" />
<img data-u="thumb" src="{% static 'home/img/thumb-09.jpg' %}" />
</div> 
<div data-p="144.50" style="display: none;">
<img data-u="image" src="{% static 'home/img/10.jpg' %}" />
<img data-u="thumb" src="{% static 'home/img/thumb-10.jpg' %}" />
</div>
<div data-p="144.50" style="display: none;">
<img data-u="image" src="{% static 'home/img/11.jpg' %}" />
<img data-u="thumb" src="{% static 'home/img/thumb-11.jpg' %}" />
</div>
<div data-p="144.50" style="display: none;">
<img data-u="image" src="{% static 'home/img/12.jpg' %}" />
<img data-u="thumb" src="{% static 'home/img/thumb-12.jpg' %}" />
</div>
<div data-p="144.50" style="display: none;">
<img data-u="image" src="{% static 'home/img/13.jpg' %}" />
<img data-u="thumb" src="{% static 'home/img/thumb-13.jpg' %}" />
</div>
<div data-p="144.50" style="display: none;">
<img data-u="image" src="{% static 'home/img/14.jpg' %}" />
<img data-u="thumb" src="{% static 'home/img/thumb-14.jpg' %}" />
</div>
</div>
<!-- Thumbnail Navigator -->
<div data-u="thumbnavigator" class="jssort01" style="position:absolute;left:0px;bottom:0px;width:800px;height:100px;" data-autocenter="1">
<!-- Thumbnail Item Skin Begin -->
<div data-u="slides" style="cursor: default;">
<div data-u="prototype" class="p">
<div class="w">
<div data-u="thumbnailtemplate" class="t"></div>
</div>
<div class="c"></div>
</div>
</div>
<!-- Thumbnail Item Skin End -->
</div>
<!-- Arrow Navigator -->
<span data-u="arrowleft" class="jssora05l" style="top:158px;left:8px;width:40px;height:40px;"></span>
<span data-u="arrowright" class="jssora05r" style="top:158px;right:8px;width:40px;height:40px;"></span>
</div>
<script type="text/javascript">jssor_1_slider_init();</script>
<!-- #endregion Jssor Slider End -->
<br><br><br><br><br><br><br>
<!-- /.container -->

    <!-- jQuery -->
    <script src="{% static 'home/js/jquery.js' %}"></script>

    


<!-- Bootstrap Core JavaScript -->
    <script src="{% static 'home/js/bootstrap.min.js' %}"></script>

</body>
{% endblock %}